# Generated by Django 2.2.4 on 2020-12-21 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Imagex',
        ),
    ]
