# Generated by Django 2.2.4 on 2020-12-21 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_auto_20201221_2249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagex',
            new_name='Image',
        ),
    ]
