# Generated by Django 2.2.4 on 2020-12-21 23:04

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_auto_20201221_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pet_img',
            field=django_resized.forms.ResizedImageField(crop=['top', 'left'], force_format=None, keep_meta=True, quality=0, size=[300, 300], upload_to='images/'),
        ),
    ]
