# Generated by Django 2.2.4 on 2020-12-21 23:11

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0006_auto_20201221_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pet_img',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=100, size=[300, 300], upload_to='images/'),
        ),
    ]
