# Generated by Django 2.2.4 on 2020-12-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0013_auto_20201225_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='desc',
            field=models.CharField(max_length=5),
        ),
    ]
