# Generated by Django 2.2.4 on 2020-12-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0015_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='users_following', to='app_one.User'),
        ),
    ]
