# Generated by Django 2.2.4 on 2020-12-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0016_auto_20201229_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='users_followers', to='app_one.User'),
        ),
    ]
