# Generated by Django 2.2.4 on 2020-12-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0017_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='being_followed', to='app_one.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='is_following', to='app_one.User'),
        ),
    ]
