# Generated by Django 2.2.4 on 2020-12-30 00:28

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0018_auto_20201229_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='png', keep_meta=True, quality=100, size=[200, 200], upload_to='images/'),
        ),
    ]
